version: 2.1

orbs:
    python: circleci/python@0.2.1

jobs:
    build-and-test:
        executor: python/default
        docker:
            - image: circleci/python:3.7-buster
        steps:
            - checkout
            - python/load-cache
            - run:
                command: ./configure
            - python/save-cache
            - run:
                command: ./test
                name: Unit Test

workflows:
    main:
        jobs:
            - build-and-test
