#!/bin/sh

# Update requirements.in and dev-requirements.in with your new dependencies
# then run this script

set -e

HEADER='# File generated by ./tools/refreeze-requirements.sh\n\n'

rm -rf venv
virtualenv venv -p $(which python3)

./venv/bin/pip install -r requirements.in
printf "$HEADER" > requirements.txt
./venv/bin/pip freeze >> requirements.txt

./venv/bin/pip install -r dev-requirements.in
printf "$HEADER" > dev-requirements.txt
./venv/bin/pip freeze >> dev-requirements.txt
