name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Configure
        run: ./configure

      - name: Run tests
        run: ./test
