name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache venv
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Configure
        run: ./configure

      - name: Run tests
        run: ./test
